services:
    mongodb:
        image: mongo:7
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
            - mongo_config:/data/configdb

volumes:
    mongo_data:
    mongo_config:
